#配置数据源
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///mydb?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root

#配置MyBatis的实体类映射
mybatis:
  type-aliases-package: con.ssm.boot.entity

server:
  tomcat:
    uri-encoding: UTF-8
  port: 8089